const config = {
        darkMode: "class",
        theme: {
          extend: {
            "colors": {
                    "surface-container-lowest": "#0e0e10",
                    "error": "#ffb4ab",
                    "error-container": "#93000a",
                    "on-secondary-container": "#d6a9ff",
                    "surface-container-low": "#1c1b1d",
                    "on-secondary-fixed": "#2c0051",
                    "primary": "#c0c1ff",
                    "on-secondary": "#490080",
                    "on-surface-variant": "#c7c4d7",
                    "on-secondary-fixed-variant": "#6900b3",
                    "on-tertiary": "#4f2500",
                    "secondary-fixed-dim": "#ddb7ff",
                    "primary-fixed-dim": "#c0c1ff",
                    "on-error": "#690005",
                    "inverse-surface": "#e5e1e4",
                    "primary-container": "#8083ff",
                    "on-primary-container": "#0d0096",
                    "on-primary": "#1000a9",
                    "on-error-container": "#ffdad6",
                    "on-primary-fixed-variant": "#2f2ebe",
                    "surface-variant": "#353437",
                    "surface-container-highest": "#353437",
                    "outline-variant": "#464554",
                    "tertiary-fixed": "#ffdcc5",
                    "tertiary": "#ffb783",
                    "on-primary-fixed": "#07006c",
                    "surface-tint": "#c0c1ff",
                    "tertiary-fixed-dim": "#ffb783",
                    "inverse-on-surface": "#313032",
                    "inverse-primary": "#494bd6",
                    "background": "#131315",
                    "surface": "#131315",
                    "surface-container-high": "#2a2a2c",
                    "on-tertiary-fixed": "#301400",
                    "surface-bright": "#39393b",
                    "secondary": "#ddb7ff",
                    "on-surface": "#e5e1e4",
                    "secondary-container": "#6f00be",
                    "on-tertiary-container": "#452000",
                    "on-tertiary-fixed-variant": "#703700",
                    "tertiary-container": "#d97721",
                    "surface-container": "#201f22",
                    "on-background": "#e5e1e4",
                    "outline": "#908fa0",
                    "surface-dim": "#131315",
                    "primary-fixed": "#e1e0ff",
                    "secondary-fixed": "#f0dbff"
            },
            "borderRadius": {
                    "DEFAULT": "0.25rem",
                    "lg": "0.5rem",
                    "xl": "0.75rem",
                    "full": "9999px"
            },
            "spacing": {
                    "base": "4px",
                    "xl": "2rem",
                    "gutter": "1.5rem",
                    "sm": "0.5rem",
                    "md": "1rem",
                    "margin": "2rem",
                    "lg": "1.5rem",
                    "xs": "0.25rem",
                    "2xl": "3rem"
            },
            "fontFamily": {
                    "headline-lg-mobile": ["Geist"],
                    "label-md": ["JetBrains Mono"],
                    "headline-lg": ["Geist"],
                    "body-sm": ["Geist"],
                    "headline-md": ["Geist"],
                    "label-sm": ["JetBrains Mono"],
                    "body-lg": ["Geist"],
                    "body-md": ["Geist"],
                    "display": ["Geist"]
            },
            "fontSize": {
                    "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
                    "label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "500" }],
                    "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
                    "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
                    "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
                    "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
                    "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
                    "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
                    "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.05em", "fontWeight": "700" }]
            }
          }
        }
      };
console.log(JSON.stringify(config.theme.extend));