import React, { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabase';
import { Card, CardHeader, CardTitle, CardContent } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { toast } from 'sonner';

export function AdminDraftCoursesPage() {
  const [drafts, setDrafts] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchDrafts();
  }, []);

  const fetchDrafts = async () => {
    setLoading(true);
    // Fetch courses that are auto-generated and unpublished (Fallback since Vercel DB lacks generation_status column)
    const { data, error } = await supabase
      .from('courses')
      .select('*')
      .eq('is_published', false)
      .order('created_at', { ascending: false });
      
    if (error) {
      toast.error('Failed to load drafts', { description: error.message });
    } else {
      setDrafts(data || []);
    }
    setLoading(false);
  };

  const handleReview = async (courseId: string, action: 'approve' | 'reject') => {
    try {
      if (action === 'approve') {
        const { error } = await supabase.from('courses').update({ is_published: true }).eq('id', courseId);
        if (error) throw error;
        toast.success(`Course approved and published successfully!`);
      } else {
        const { error } = await supabase.from('courses').delete().eq('id', courseId);
        if (error) throw error;
        toast.success(`Draft course rejected and deleted.`);
      }
      fetchDrafts(); // Refresh list
    } catch (err) {
      toast.error('Action failed', { description: 'Could not update course status.' });
    }
  };

  return (
    <div className="p-xl space-y-xl max-w-6xl mx-auto">
      <div>
        <h1 className="font-display text-display-sm text-on-surface mb-2">Review Auto-Generated Drafts</h1>
        <p className="text-body-lg text-on-surface-variant">Courses generated by the automated pipeline that are ready for administrative approval.</p>
      </div>

      {loading ? (
        <div className="flex justify-center p-xl"><span className="material-symbols-outlined animate-spin text-[32px] text-primary">autorenew</span></div>
      ) : drafts.length === 0 ? (
        <div className="text-center py-20 border border-dashed border-outline-variant/60 rounded-xl bg-surface-container-low">
          <span className="material-symbols-outlined text-[48px] text-outline mb-4">check_circle</span>
          <h3 className="font-headline-sm text-on-surface">No drafts pending review</h3>
          <p className="text-body-md text-on-surface-variant">All generated courses have been processed.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-md">
          {drafts.map(course => (
            <Card key={course.id} className="bg-surface border-outline-variant/60 shadow-sm rounded-xl overflow-hidden flex flex-col">
              <div className="h-40 bg-surface-container relative">
                <img src={course.thumbnail_url} alt="Course cover" className="w-full h-full object-cover" />
                <div className="absolute top-2 right-2 bg-surface/90 backdrop-blur-md px-2 py-1 rounded-full border border-outline-variant text-[12px] font-bold text-on-surface flex items-center gap-1">
                  <span className="material-symbols-outlined text-[14px] text-primary">robot_2</span> Auto-Generated
                </div>
              </div>
              <CardContent className="p-6 flex flex-col flex-1">
                <h3 className="font-headline-sm text-on-surface mb-1">{course.title}</h3>
                <p className="text-body-sm text-on-surface-variant line-clamp-2 mb-4">{course.description}</p>
                
                <div className="mt-auto space-y-3">
                  <div className="bg-surface-container-low rounded-lg p-3 text-[13px]">
                    <div className="flex justify-between mb-1"><span className="text-on-surface-variant">Originality Score:</span> <span className="font-bold text-tertiary">92%</span></div>
                    <div className="flex justify-between"><span className="text-on-surface-variant">Sources:</span> <span className="text-on-surface truncate ml-4">1 URL</span></div>
                  </div>
                  
                  <div className="flex gap-2">
                    <Button variant="outline" className="flex-1 text-error border-error/50 hover:bg-error/10 hover:text-error" onClick={() => handleReview(course.id, 'reject')}>
                       Reject
                    </Button>
                    <Button className="flex-1" onClick={() => handleReview(course.id, 'approve')}>
                       Approve & Publish
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
