import { createClient } from '@supabase/supabase-js';

// Vercel serverless function handler
export default async function handler(req: any, res: any) {
  // Only allow GET or POST
  if (req.method !== 'GET' && req.method !== 'POST') {
    return res.status(405).json({ message: 'Method Not Allowed' });
  }

  // Ensure authorization for cron (Vercel automatically sends this header)
  const authHeader = req.headers.authorization;
  if (process.env.CRON_SECRET && authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return res.status(401).json({ message: 'Unauthorized' });
  }

  // Initialize Supabase client
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  // MUST use Service Role Key to bypass RLS and insert!
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Supabase credentials.');
    return res.status(500).json({ error: 'Missing Database Configuration' });
  }

  const supabase = createClient(supabaseUrl, supabaseKey);

  try {
    console.log('[Cron] Starting daily automated scraping pipeline...');
    
    // Define the sources to scrape today
    const targetTopics = ['Machine Learning Basics', 'Advanced System Design', 'Web3 Architecture'];
    const generatedCourses = [];
    
    // Simulate scraping and generation for each topic
    for (const topic of targetTopics) {
      console.log(`[Cron] Scraping and generating course for: ${topic}`);
      
      const title = `${topic}: Automated Daily Masterclass`;
      const description = `This course was automatically generated by the LearnLoom Scraping Engine on ${new Date().toISOString().split('T')[0]}. It covers the fundamentals and advanced patterns of ${topic}.`;
      
      // Construct the database payload
      const dbPayload = {
        title,
        description,
        thumbnail_url: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800&q=80',
        difficulty_level: 'intermediate',
        is_published: false, // Critical: MUST remain a draft
        tags: ['auto-generated', 'daily-cron'],
        price: 49.99
      };
      
      // Insert into database
      const { data, error } = await supabase.from('courses').insert(dbPayload).select();
      
      if (error) {
        console.error(`[Cron] Failed to insert ${topic}:`, error);
      } else {
        generatedCourses.push(data[0]);
      }
    }
    
    console.log(`[Cron] Successfully generated ${generatedCourses.length} courses.`);
    return res.status(200).json({ 
      success: true, 
      message: `Generated ${generatedCourses.length} courses.`,
      courses: generatedCourses
    });

  } catch (error: any) {
    console.error('[Cron] Pipeline execution error:', error);
    return res.status(500).json({ success: false, error: error.message });
  }
}
